### ISSUE TITLE
Ativar 5Ghz

### ISSUE THREAD

**Issue by Rickplay4924** [Magisk-Modules-Repo/wifi5ghzdisabler#3]
Usei o módulo para desativar o 5ghz do meu aparelho, porém estou precisando agora da banda 5Ghz. 
Como faço pra reativar?

Redmi 5 plus (vince) global

**Comment by danielchc** [comment]
Olá, se você desativa (ou desinstala) o módulo no Magisk, o wifi 5Ghz já deveria funcionar 😄

**Comment by Rickplay4924** [comment]
Desinstalei e não voltou ao normal.
Então instalei o módulo "Wifi bonding (Qcom)" no magisk e tudo voltou a funcionar, 2.4Ghz & 5Ghz.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
